version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    networks:
      - backend-network

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Mdpsecurise12."
      QL_PID: "Developer"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver-data:/var/opt/sql-server
      - ./data/sql-server/init:/var/opt/sql-server/scripts

    networks:
      - backend-network
    command: 
      - /bin/bash
      - -c
      - |
        /opt/mssql/bin/sqlservr & sleep 10;
        /opt/mssql-tools/bin/sqlcmd -S localhost -U SA -P "Mdpsecurise12." -d master -i /var/opt/sql-server/scripts/init-sql-server.sql
        wait

volumes:
  mongodb-data:
    driver: local
  sqlserver-data:
    driver: local

networks:
  backend-network:
    driver: bridge
